package com.app.packs.web.soap.prepaidService.impl;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.app.packs.web.soap.prepaidService.service.PrepaidService;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-07T09:12:03.195-03:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "PrepaidServiceImplService", 
                  wsdlLocation = "file:PrepaidService.wsdl",
                  targetNamespace = "http://impl.service.testprepaidservice.redmondsoftware.com.ar/") 
public class PrepaidServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.testprepaidservice.redmondsoftware.com.ar/", "PrepaidServiceImplService");
    public final static QName PrepaidServiceImplPort = new QName("http://impl.service.testprepaidservice.redmondsoftware.com.ar/", "PrepaidServiceImplPort");
    static {
        URL url = null;
        url = PrepaidServiceImplService.class.getClassLoader().getResource("wsdl/PrepaidService.wsdl");
        WSDL_LOCATION = url;
    }

    public PrepaidServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PrepaidServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrepaidServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PrepaidServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PrepaidServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PrepaidServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PrepaidService
     */
    @WebEndpoint(name = "PrepaidServiceImplPort")
    public PrepaidService getPrepaidServiceImplPort() {
        return super.getPort(PrepaidServiceImplPort, PrepaidService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrepaidService
     */
    @WebEndpoint(name = "PrepaidServiceImplPort")
    public PrepaidService getPrepaidServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PrepaidServiceImplPort, PrepaidService.class, features);
    }

}
