package com.app.packs.web.soap.prepaidService.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.app.packs.web.soap.prepaidService.jaxbClasses.BoltonOperationRequest;
import com.app.packs.web.soap.prepaidService.jaxbClasses.DeleteBoltonResponse;
import com.app.packs.web.soap.prepaidService.jaxbClasses.GetPlanForUserResponse;
import com.app.packs.web.soap.prepaidService.jaxbClasses.ObjectFactory;
import com.app.packs.web.soap.prepaidService.jaxbClasses.PurchaseBoltonResponse;
import com.app.packs.web.soap.prepaidService.jaxbClasses.UserOperationRequest;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-07T09:12:03.156-03:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://service.testprepaidservice.redmondsoftware.com.ar/", name = "PrepaidService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PrepaidService {

    @WebResult(name = "deleteBoltonResponse", targetNamespace = "http://service.testprepaidservice.redmondsoftware.com.ar/", partName = "parameters")
    @WebMethod
    public DeleteBoltonResponse deleteBolton(
        @WebParam(partName = "parameters", name = "deleteBoltonRequest", targetNamespace = "http://service.testprepaidservice.redmondsoftware.com.ar/")
        BoltonOperationRequest parameters
    );

    @WebResult(name = "getPlanForUserResponse", targetNamespace = "http://service.testprepaidservice.redmondsoftware.com.ar/", partName = "parameters")
    @WebMethod
    public GetPlanForUserResponse getPlanForUser(
        @WebParam(partName = "parameters", name = "getPlanForUserRequest", targetNamespace = "http://service.testprepaidservice.redmondsoftware.com.ar/")
        UserOperationRequest parameters
    );

    @WebResult(name = "purchaseBoltonResponse", targetNamespace = "http://service.testprepaidservice.redmondsoftware.com.ar/", partName = "parameters")
    @WebMethod
    public PurchaseBoltonResponse purchaseBolton(
        @WebParam(partName = "parameters", name = "purchaseBoltonRequest", targetNamespace = "http://service.testprepaidservice.redmondsoftware.com.ar/")
        BoltonOperationRequest parameters
    );
}
